import type { Recipe } from "./pantry-types";

export const peruvianRecipes: Recipe[] = [
  {
    id: "pe1",
    name: "Lomo Saltado",
    meal: "almuerzo",
    minutes: 30,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Lomo-saltado-perudelights.jpg/500px-Lomo-saltado-perudelights.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 2,
    main: ["Carne de res", "Cebolla", "Tomate", "Papa"],
    basics: ["Sillao", "Vinagre", "Aceite", "Sal"],
    steps: [
      "Fríe las papas.",
      "Saltea la carne a fuego alto.",
      "Añade cebolla, tomate, sillao y vinagre.",
      "Mezcla con las papas y sirve con arroz.",
    ],
  },
  {
    id: "pe2",
    name: "Ceviche de Pescado",
    meal: "almuerzo",
    minutes: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ceviche_at_Peru.jpg/500px-Ceviche_at_Peru.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 2,
    main: ["Pescado", "Limón", "Cebolla morada", "Ají limo"],
    basics: ["Sal", "Culantro"],
    steps: [
      "Corta el pescado en cubos.",
      "Sazona con sal y ají.",
      "Agrega el jugo de limón y cebolla en pluma.",
      "Sirve con camote y choclo.",
    ],
  },
  {
    id: "pe3",
    name: "Ají de Gallina",
    meal: "almuerzo",
    minutes: 45,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Aj%C3%AD_de_gallina_-_Tradicional.jpg/500px-Aj%C3%AD_de_gallina_-_Tradicional.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Pechuga de pollo", "Ají amarillo", "Pan", "Leche"],
    basics: ["Ajo", "Cebolla", "Sal", "Pecanas"],
    steps: [
      "Sancocha y deshilacha el pollo.",
      "Licúa el pan con la leche.",
      "Haz un aderezo con cebolla, ajo y ají amarillo.",
      "Mezcla todo, deja espesar y sirve con huevo duro.",
    ],
  },
  {
    id: "pe4",
    name: "Papa a la Huancaína",
    meal: "entrada",
    minutes: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Papa_huancaina.jpg/500px-Papa_huancaina.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Papa amarilla", "Queso fresco", "Ají amarillo", "Leche"],
    basics: ["Galleta de soda", "Aceite", "Sal"],
    steps: [
      "Sancocha las papas.",
      "Licúa el queso, ají, leche y galletas hasta formar una crema.",
      "Baña las papas con la crema y decora con huevo y aceituna.",
    ],
  },
  {
    id: "pe5",
    name: "Causa Rellena",
    meal: "entrada",
    minutes: 40,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Causa_Rellena.jpg/500px-Causa_Rellena.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Papa amarilla", "Pollo", "Limón", "Palta"],
    basics: ["Ají amarillo", "Mayonesa", "Sal"],
    steps: [
      "Prensa las papas cocidas y mezcla con limón y ají.",
      "Deshilacha el pollo y mezcla con mayonesa.",
      "Arma capas de papa, palta y relleno de pollo.",
    ],
  },
  {
    id: "pe6",
    name: "Anticuchos de Corazón",
    meal: "cena",
    minutes: 60,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Anticuchos_de_la_Tia_Grima.jpg/500px-Anticuchos_de_la_Tia_Grima.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Corazón de res", "Ají panca", "Vinagre", "Papas"],
    basics: ["Ajo", "Comino", "Sal", "Aceite"],
    steps: [
      "Corta el corazón en trozos.",
      "Macera con ají panca, vinagre y especias.",
      "Ensarta en palitos y fríe a la parrilla.",
      "Sirve con papas doradas.",
    ],
  },
  {
    id: "pe7",
    name: "Arroz con Pollo",
    meal: "almuerzo",
    minutes: 50,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/TW_%E5%8F%B0%E7%81%A3_Taiwan_%E4%B8%AD%E6%AD%A3%E5%8D%80_Zhongzheng_District_%E9%BC%8E%E6%B3%B0%E8%B1%90_Din_Tai_Fung_restaurant_dinner_August_2019_IX2_12.jpg/500px-TW_%E5%8F%B0%E7%81%A3_Taiwan_%E4%B8%AD%E6%AD%A3%E5%8D%80_Zhongzheng_District_%E9%BC%8E%E6%B3%B0%E8%B1%90_Din_Tai_Fung_restaurant_dinner_August_2019_IX2_12.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Pollo", "Arroz", "Culantro", "Zanahoria"],
    basics: ["Alverjitas", "Cebolla", "Ajo", "Cerveza negra"],
    steps: [
      "Dora el pollo y reserva.",
      "Haz un aderezo con culantro licuado.",
      "Agrega el arroz, pollo, cerveza y agua.",
      "Cocina a fuego lento hasta granear.",
    ],
  },
  {
    id: "pe8",
    name: "Tallarines Verdes",
    meal: "almuerzo",
    minutes: 30,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Taglioni_side.png/500px-Taglioni_side.png?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Fideos", "Albahaca", "Espinaca", "Queso fresco"],
    basics: ["Leche", "Ajo", "Sal", "Aceite"],
    steps: [
      "Hierve los fideos.",
      "Licúa albahaca, espinaca, queso, leche y ajo.",
      "Mezcla la salsa con los fideos.",
      "Sirve acompañado de un bistec.",
    ],
  },
  {
    id: "pe9",
    name: "Tacu Tacu",
    meal: "almuerzo",
    minutes: 25,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Tacu_Tacu.jpg/500px-Tacu_Tacu.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 2,
    main: ["Frijoles cocidos", "Arroz cocido", "Ají amarillo"],
    basics: ["Cebolla", "Ajo", "Aceite", "Sal"],
    steps: [
      "Mezcla el arroz y los frijoles.",
      "Haz un aderezo de cebolla y ají.",
      "Agrega la mezcla y fríe hasta formar una masa dorada.",
      "Sirve con huevo frito y plátano.",
    ],
  },
  {
    id: "pe10",
    name: "Rocoto Relleno",
    meal: "entrada",
    minutes: 90,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/%22rocoto%22_relleno.jpg/500px-%22rocoto%22_relleno.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Rocoto", "Carne molida", "Queso", "Papa"],
    basics: ["Cebolla", "Ajo", "Huevo", "Leche"],
    steps: [
      "Limpia y hierve los rocotos.",
      "Prepara el relleno de carne con cebolla y pasas.",
      "Rellena los rocotos y cubre con queso.",
      "Hornea junto a un pastel de papa.",
    ],
  },
  {
    id: "pe11",
    name: "Carapulcra",
    meal: "almuerzo",
    minutes: 60,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Carapulcra_y_Sopa_Seca_en_Lima_Peru.jpg/500px-Carapulcra_y_Sopa_Seca_en_Lima_Peru.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Papa seca", "Chancho", "Ají panca", "Maní"],
    basics: ["Cebolla", "Ajo", "Comino", "Sal"],
    steps: [
      "Tuesta y remoja la papa seca.",
      "Haz un aderezo con ají panca y cerdo.",
      "Agrega la papa seca y caldo.",
      "Cocina a fuego lento y añade maní al final.",
    ],
  },
  {
    id: "pe12",
    name: "Cau Cau",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Caucau.jpg/500px-Caucau.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Mondongo", "Papa blanca", "Hierbabuena", "Palillo"],
    basics: ["Cebolla", "Ajo", "Ají amarillo", "Sal"],
    steps: [
      "Cocina y corta el mondongo en cubos.",
      "Prepara un aderezo con palillo y ají.",
      "Añade papas en cubos y mondongo.",
      "Cocina y aromatiza con hierbabuena.",
    ],
  },
  {
    id: "pe13",
    name: "Ocopa Arequipeña",
    meal: "entrada",
    minutes: 25,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Ocopa_%28Peru%29.JPG/500px-Ocopa_%28Peru%29.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Papa hervida", "Huacatay", "Queso fresco", "Maní"],
    basics: ["Ají amarillo", "Leche", "Galleta", "Cebolla"],
    steps: [
      "Sofríe ají, cebolla y huacatay.",
      "Licúa con queso, maní, leche y galletas.",
      "Sirve la crema sobre papas hervidas.",
      "Decora con huevo duro.",
    ],
  },
  {
    id: "pe14",
    name: "Seco de Carne",
    meal: "almuerzo",
    minutes: 60,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Carne de res", "Culantro", "Alverjas", "Zanahoria"],
    basics: ["Cebolla", "Ajo", "Ají amarillo", "Chicha de jora"],
    steps: [
      "Dora la carne.",
      "Haz un aderezo y licúa el culantro.",
      "Mezcla todo con chicha de jora y verduras.",
      "Cocina a fuego bajo hasta que la carne esté suave.",
    ],
  },
  {
    id: "pe15",
    name: "Chupe de Camarones",
    meal: "almuerzo",
    minutes: 45,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Chupe_de_Camarones.jpg/500px-Chupe_de_Camarones.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Camarones", "Papa amarilla", "Arroz", "Leche evaporada"],
    basics: ["Queso fresco", "Huevo", "Huacatay", "Ají panca"],
    steps: [
      "Haz un caldo con las cabezas de camarón.",
      "Prepara un aderezo y añade el caldo, arroz y papa.",
      "Agrega camarones, queso y huevo.",
      "Finaliza con leche y huacatay.",
    ],
  },
  {
    id: "pe16",
    name: "Pollo a la Brasa",
    meal: "cena",
    minutes: 120,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Pollo entero", "Papas amarillas"],
    basics: ["Sillao", "Cerveza negra", "Comino", "Romero"],
    steps: [
      "Macera el pollo con las especias y líquidos.",
      "Hornea o rostiza hasta que dore.",
      "Fríe papas en bastones.",
      "Sirve con ensalada fresca y cremas.",
    ],
  },
  {
    id: "pe17",
    name: "Pachamanca a la Olla",
    meal: "almuerzo",
    minutes: 90,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Pachamanca_Peru.JPG/500px-Pachamanca_Peru.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Pollo", "Papa", "Camote", "Choclo"],
    basics: ["Huacatay", "Chincho", "Ají panca", "Ajo"],
    steps: [
      "Macera las carnes con huacatay y chincho licuados.",
      "Acomoda en una olla capas de carne y tubérculos.",
      "Cocina a fuego lento y tapado al vapor.",
    ],
  },
  {
    id: "pe18",
    name: "Cuy Chactado",
    meal: "almuerzo",
    minutes: 45,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Cuy_Chactado.jpg/500px-Cuy_Chactado.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 2,
    main: ["Cuy entero", "Papa", "Maíz tostado"],
    basics: ["Ajo", "Ají panca", "Sal", "Aceite"],
    steps: [
      "Sazona el cuy con ajo y ají.",
      "Fríe en abundante aceite tapado con una piedra.",
      "Sirve dorado y crocante con papas.",
    ],
  },
  {
    id: "pe19",
    name: "Juane de Gallina",
    meal: "almuerzo",
    minutes: 90,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Juane_3260409.JPG/500px-Juane_3260409.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Arroz", "Gallina", "Huevo duro", "Hojas de bijao"],
    basics: ["Guisador", "Aceite", "Ajo", "Aceituna"],
    steps: [
      "Prepara un arroz con guisador.",
      "Cocina la gallina en aderezo.",
      "Envuelve arroz, gallina, huevo y aceituna en hoja de bijao.",
      "Hierve los paquetes formados por 30 min.",
    ],
  },
  {
    id: "pe20",
    name: "Arroz Chaufa",
    meal: "cena",
    minutes: 25,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Arroz cocido", "Pollo", "Huevo", "Cebollita china"],
    basics: ["Sillao", "Aceite de ajonjolí", "Kion", "Aceite"],
    steps: [
      "Fríe el huevo en tortilla y corta.",
      "Saltea pollo con kion.",
      "Agrega arroz, sillao y aceite de ajonjolí.",
      "Añade cebollita china y huevo antes de servir.",
    ],
  },
  {
    id: "pe21",
    name: "Sopa Seca",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Carapulcra_y_Sopa_Seca_en_Lima_Peru.jpg/500px-Carapulcra_y_Sopa_Seca_en_Lima_Peru.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Fideos", "Pollo desmenuzado", "Albahaca", "Tomate"],
    basics: ["Ajo", "Cebolla", "Aceite", "Achiete"],
    steps: [
      "Haz un aderezo con tomate, albahaca y pollo.",
      "Agrega caldo y los fideos crudos.",
      "Cocina a fuego lento hasta que los fideos absorban el líquido.",
    ],
  },
  {
    id: "pe22",
    name: "Locro de Zapallo",
    meal: "almuerzo",
    minutes: 35,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Locro_argentino.jpg/500px-Locro_argentino.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Zapallo macre", "Papa", "Queso fresco", "Choclo"],
    basics: ["Cebolla", "Huacatay", "Leche", "Ajo"],
    steps: [
      "Haz un aderezo y cocina el zapallo picado con papa y choclo.",
      "Espera que el zapallo se deshaga.",
      "Añade queso, huacatay y un chorrito de leche.",
    ],
  },
  {
    id: "pe23",
    name: "Pescado a lo Macho",
    meal: "almuerzo",
    minutes: 30,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Filete de pescado", "Mariscos mixtos", "Ají panca", "Ají amarillo"],
    basics: ["Cebolla", "Tomate", "Vino blanco", "Harina"],
    steps: [
      "Pasa el pescado por harina y fríe.",
      "Haz un aderezo picante y añade los mariscos con vino blanco.",
      "Espera que reduzca y baña el pescado con esta salsa.",
    ],
  },
  {
    id: "pe24",
    name: "Jalea Mixta",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Pescado", "Mariscos", "Yuca", "Cebolla morada"],
    basics: ["Harina", "Limón", "Sal", "Aceite"],
    steps: [
      "Empaniza pescado y mariscos.",
      "Fríe en abundante aceite.",
      "Fríe yucas en bastones.",
      "Sirve cubierto con salsa criolla.",
    ],
  },
  {
    id: "pe25",
    name: "Tiradito",
    meal: "entrada",
    minutes: 15,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Pescado fresco", "Ají amarillo", "Limón", "Camote"],
    basics: ["Ajo", "Kion", "Sal"],
    steps: [
      "Corta el pescado en láminas delgadas.",
      "Licúa limón, ají amarillo y kion.",
      "Baña el pescado con la crema.",
      "Sirve frío con camote y choclo.",
    ],
  },
  {
    id: "pe26",
    name: "Adobo Arequipeño",
    meal: "desayuno",
    minutes: 90,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Carne de cerdo", "Concho de chicha", "Cebolla roja", "Rocoto"],
    basics: ["Ajo", "Comino", "Orégano"],
    steps: [
      "Macera el cerdo en la chicha y especias desde el día anterior.",
      "Cocina a fuego lento con mucha cebolla.",
      "Sirve jugoso acompañado de pan de tres puntas.",
    ],
  },
  {
    id: "pe27",
    name: "Chicharrón de Cerdo",
    meal: "desayuno",
    minutes: 60,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Panceta de cerdo", "Camote", "Cebolla", "Pan"],
    basics: ["Sal", "Hierbabuena", "Aceite"],
    steps: [
      "Hierve el cerdo en agua con sal hasta que se seque.",
      "Deja que se fría en su propia grasa.",
      "Sirve en pan con camote frito y salsa criolla.",
    ],
  },
  {
    id: "pe28",
    name: "Sudado de Pescado",
    meal: "almuerzo",
    minutes: 25,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Pescado entero", "Tomate", "Cebolla", "Culantro"],
    basics: ["Ají amarillo", "Ajo", "Chicha de jora"],
    steps: [
      "Haz una cama de cebolla y tomate en una olla.",
      "Coloca el pescado sazonado encima.",
      "Agrega chicha de jora y suda a fuego medio por 15 min.",
    ],
  },
  {
    id: "pe29",
    name: "Shambar",
    meal: "almuerzo",
    minutes: 120,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 6,
    main: ["Trigo shambar", "Frijoles", "Garbanzos", "Costilla de cerdo"],
    basics: ["Pellejo de cerdo", "Hierbabuena", "Ají panca"],
    steps: [
      "Remoja y cocina las menestras y el trigo.",
      "Haz un aderezo y hierve junto con las carnes.",
      "Cocina hasta espesar y sirve con cancha serrana.",
    ],
  },
  {
    id: "pe30",
    name: "Patasca",
    meal: "desayuno",
    minutes: 180,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 6,
    main: ["Mote", "Mondongo", "Carne de res", "Hierbabuena"],
    basics: ["Ajo", "Cebolla", "Sal", "Limón"],
    steps: [
      "Hierve el mote hasta que reviente.",
      "Añade mondongo y carne, cocinando hasta suavizar.",
      "Sazona y aromatiza con hierbabuena.",
    ],
  },
  {
    id: "pe31",
    name: "Olluquito con Charqui",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Olluco picado", "Charqui", "Papa", "Perejil"],
    basics: ["Ají panca", "Cebolla", "Ajo", "Aceite"],
    steps: [
      "Lava y pica los ollucos en juliana.",
      "Haz un aderezo de ají panca y sofríe el charqui.",
      "Agrega el olluco y cocina tapado sin agua extra.",
    ],
  },
  {
    id: "pe32",
    name: "Puca Picante",
    meal: "almuerzo",
    minutes: 45,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Papa nativa", "Maní tostado", "Betarraga", "Carne de cerdo"],
    basics: ["Ají panca", "Ajo", "Cebolla", "Comino"],
    steps: [
      "Dora la carne de cerdo.",
      "Prepara el aderezo de ají panca y licúa con betarraga y maní.",
      "Mezcla con papas hervidas y la carne.",
    ],
  },
  {
    id: "pe33",
    name: "Tallarín Saltado",
    meal: "cena",
    minutes: 25,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Fideos chinos", "Pollo", "Holantao", "Pimiento"],
    basics: ["Sillao", "Aceite de ajonjolí", "Kion"],
    steps: [
      "Cocina los fideos crudos.",
      "Saltea pollo y verduras a fuego muy alto.",
      "Mezcla fideos, sillao y sirve caliente.",
    ],
  },
  {
    id: "pe34",
    name: "Choritos a la Chalaca",
    meal: "entrada",
    minutes: 20,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Choros", "Cebolla morada", "Tomate", "Choclo"],
    basics: ["Limón", "Rocoto", "Culantro", "Sal"],
    steps: [
      "Limpia y hierve los choros.",
      "Pica finamente la cebolla, tomate, rocoto y culantro.",
      "Mezcla con choclo y limón.",
      "Coloca la mezcla sobre cada choro en su valva.",
    ],
  },
  {
    id: "pe35",
    name: "Empanadas Peruanas",
    meal: "snack",
    minutes: 90,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cuisine_Peru_Menestron.jpg/500px-Cuisine_Peru_Menestron.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 6,
    main: ["Masa hojaldre", "Carne molida", "Huevo duro", "Aceituna"],
    basics: ["Cebolla", "Azúcar glass", "Huevo batido"],
    steps: [
      "Prepara un relleno jugoso de carne.",
      "Arma las empanadas con carne, huevo y aceituna.",
      "Barniza con huevo y hornea.",
      "Espolvorea azúcar y sirve con limón.",
    ],
  },
  {
    id: "pe36",
    name: "Pastel de Papa",
    meal: "guarnición",
    minutes: 60,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ceviche_at_Peru.jpg/500px-Ceviche_at_Peru.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 6,
    main: ["Papa blanca", "Leche evaporada", "Queso fresco", "Huevos"],
    basics: ["Anís", "Mantequilla", "Sal"],
    steps: [
      "Corta papas en rodajas delgadas.",
      "En un molde pon capas de papa y queso.",
      "Bate leche, huevos y anís, y viértelo.",
      "Hornea hasta gratinar.",
    ],
  },
  {
    id: "pe37",
    name: "Escabeche de Pollo",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Bonito_escabeche_%28tapa%29.jpg/500px-Bonito_escabeche_%28tapa%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Presas de pollo", "Cebolla gruesa", "Ají amarillo", "Vinagre"],
    basics: ["Camote", "Huevo duro", "Aceituna", "Orégano"],
    steps: [
      "Fríe el pollo.",
      "Saltea la cebolla en trozos grandes con ají amarillo y vinagre.",
      "Cubre el pollo con la cebolla y reposa.",
      "Sirve frío o templado con camote.",
    ],
  },
  {
    id: "pe38",
    name: "Aguadito de Pollo",
    meal: "cena",
    minutes: 45,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Aguadito.jpg/500px-Aguadito.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Pollo", "Arroz", "Culantro", "Alverjas"],
    basics: ["Zanahoria", "Ají amarillo", "Ajo", "Caldo"],
    steps: [
      "Dora las presas de pollo.",
      "Haz un aderezo y licúa el culantro.",
      "Añade abundante caldo, verduras y un poco de arroz.",
      "Cocina hasta que quede caldoso.",
    ],
  },
  {
    id: "pe39",
    name: "Chanfainita",
    meal: "almuerzo",
    minutes: 60,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Chanfainita_con_arroz_y_mote_Chiqui%C3%A1n_01112009.JPG/500px-Chanfainita_con_arroz_y_mote_Chiqui%C3%A1n_01112009.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Bofe de res", "Papa blanca", "Mote", "Hierbabuena"],
    basics: ["Ají panca", "Cebolla", "Ajo", "Orégano"],
    steps: [
      "Limpia y hierve el bofe, luego pícalo.",
      "Haz aderezo de panca, agrega papa picada y bofe.",
      "Cocina lentamente y perfuma con hierbabuena.",
    ],
  },
  {
    id: "pe40",
    name: "Sangrecita",
    meal: "desayuno",
    minutes: 30,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Sangrecita_con_yuca.jpg/500px-Sangrecita_con_yuca.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Sangre de pollo", "Cebolla china", "Ají limo", "Papa"],
    basics: ["Ajo", "Hierbabuena", "Aceite"],
    steps: [
      "Hierve la sangre y pícala muy fino.",
      "Haz un aderezo base con cebolla y ají.",
      "Fríe la sangre sazonada.",
      "Acompaña con papas doradas y yuca.",
    ],
  },
  {
    id: "pe41",
    name: "Sopa a la Minuta",
    meal: "cena",
    minutes: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cuisine_Peru_Menestron.jpg/500px-Cuisine_Peru_Menestron.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 2,
    main: ["Carne molida", "Fideos cabello de ángel", "Leche", "Huevo"],
    basics: ["Ají panca", "Orégano", "Cebolla", "Pan tostado"],
    steps: [
      "Sofríe la carne con cebolla y ají panca.",
      "Agrega agua y hierve.",
      "Añade los fideos y huevo pochado.",
      "Apaga el fuego, echa leche y orégano.",
    ],
  },
  {
    id: "pe42",
    name: "Menestrón",
    meal: "almuerzo",
    minutes: 60,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Carne de res", "Fideos macarrón", "Albahaca", "Frijoles verdes"],
    basics: ["Zapallo", "Papa", "Choclo", "Queso"],
    steps: [
      "Haz un caldo concentrado de carne y verduras.",
      "Licúa albahaca, queso y ajo.",
      "Agrega fideos al caldo y al final la salsa verde.",
    ],
  },
  {
    id: "pe43",
    name: "Tacacho con Cecina",
    meal: "almuerzo",
    minutes: 40,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Plátano verde", "Cecina de cerdo", "Manteca de cerdo"],
    basics: ["Sal", "Chicharrón de cerdo"],
    steps: [
      "Asa o fríe los plátanos verdes.",
      "Machácalos con manteca y trozos de chicharrón, formando bolas.",
      "Fríe la cecina y sirve caliente.",
    ],
  },
  {
    id: "pe44",
    name: "Inchicapi",
    meal: "almuerzo",
    minutes: 50,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Gallina", "Maní", "Harina de maíz", "Culantro"],
    basics: ["Sacha culantro", "Ajo", "Yuca"],
    steps: [
      "Hierve la gallina para hacer caldo.",
      "Licúa maní, harina de maíz y culantro.",
      "Espesa el caldo con este licuado.",
      "Sirve con yuca cocida.",
    ],
  },
  {
    id: "pe45",
    name: "Patarashca",
    meal: "almuerzo",
    minutes: 30,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 2,
    main: ["Pescado de río", "Hoja de bijao", "Cebolla", "Ají dulce"],
    basics: ["Ajo", "Sacha culantro", "Aceite"],
    steps: [
      "Limpia el pescado.",
      "Rellena con un picadillo de verduras amazónicas.",
      "Envuelve en hoja de bijao.",
      "Asa a la parrilla o al carbón.",
    ],
  },
  {
    id: "pe46",
    name: "Ensalada de Pallares",
    meal: "entrada",
    minutes: 20,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Pallares cocidos", "Cebolla roja", "Tomate", "Limón"],
    basics: ["Aceite de oliva", "Orégano", "Perejil", "Sal"],
    steps: [
      "Sancocha los pallares.",
      "Mezcla con cebolla en pluma y tomate.",
      "Aliña con limón, aceite, sal y orégano.",
    ],
  },
  {
    id: "pe47",
    name: "Frejoles con Seco",
    meal: "almuerzo",
    minutes: 90,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400",
    servings: 4,
    main: ["Frejoles canario", "Carne", "Culantro", "Arroz"],
    basics: ["Ajo", "Cebolla", "Panceta", "Sal"],
    steps: [
      "Cocina los frejoles con un trozo de tocino.",
      "Haz un guiso de seco de carne.",
      "Sirve arroz, frejoles y el guiso encima.",
    ],
  },
  {
    id: "pe48",
    name: "Humitas",
    meal: "desayuno",
    minutes: 60,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Humitas_por_Claudio.N%C3%BA%C3%B1ez.jpg/500px-Humitas_por_Claudio.N%C3%BA%C3%B1ez.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 6,
    main: ["Choclo rallado", "Queso fresco", "Pancas de choclo", "Manteca"],
    basics: ["Azúcar o sal", "Anís", "Pasas"],
    steps: [
      "Ralla el choclo y mezcla con manteca.",
      "Añade azúcar, pasas.",
      "Envuelve en las pancas de choclo.",
      "Cocina al vapor por 40 min.",
    ],
  },
  {
    id: "pe49",
    name: "Tamales Peruanos",
    meal: "desayuno",
    minutes: 120,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/%C3%91a_Goyita_la_tamalera_%281850%29.jpg/500px-%C3%91a_Goyita_la_tamalera_%281850%29.jpg?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 6,
    main: ["Mote", "Pollo o Cerdo", "Hoja de plátano", "Ají panca"],
    basics: ["Manteca", "Aceituna", "Maní", "Huevo duro"],
    steps: [
      "Prepara masa de maíz con manteca y caldo.",
      "Haz relleno con ají panca y carnes.",
      "Arma el tamal en hoja de plátano.",
      "Hierve por largo tiempo.",
    ],
  },
  {
    id: "pe50",
    name: "Arroz con Pato",
    meal: "almuerzo",
    minutes: 90,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Arroz_con_pato_a_la_chiclayana.JPG/500px-Arroz_con_pato_a_la_chiclayana.JPG?utm_source=es.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    servings: 4,
    main: ["Pato", "Arroz", "Culantro", "Cerveza negra"],
    basics: ["Pisco", "Zapallo loche", "Ají amarillo"],
    steps: [
      "Macera el pato con pisco y dora.",
      "Haz un aderezo con culantro y zapallo loche rallado.",
      "Agrega arroz, cerveza y cocina a fuego lento.",
    ],
  },
];
